# Generated by Django 5.0.8 on 2024-08-10 14:46

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Token",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("hash", models.CharField(editable=False, max_length=64, unique=True)),
                ("system", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name": "Token",
                "verbose_name_plural": "Tokens",
                "db_table": "tb_tokens",
            },
        ),
    ]
