[default]
DB_ENGINE = "mssql"
DB_NAME = "sed"
DB_USER = "sed"
DB_PASSWORD = "@myStrongPassword"
DB_HOST = "localhost"
DB_PORT = "1433"

ENVIRONMENT = "dev"
EMAIL_TEST_MODE = true
TEST_EMAIL_RECIPIENT = "9f5aa5ac42-1e02fd@inbox.mailtrap.io"

EMAIL_HOST = "localhost"
EMAIL_PORT = 1025
EMAIL_USE_TLS = false
EMAIL_HOST_USER = ""
EMAIL_HOST_PASSWORD = ""

EMAIL_HOST_SENDER = "9f5aa5ac42-1e02fd@inbox.mailtrap.io"
